module.exports = {
  TYPE: { DEFAULT: 1 },
  PROJECT_INTERFACE_TYPE: {
    OWNER: 1,
    MAINTAINER: 2,
    DEVELOPER: 3,
    GUEST: 5,
  },
  ROUTE_GENERATE_TYPE: {
    AUTO: 1,
    MANUAL: 2,
  },
  CONSTANT_GENERATE_TYPE: {
    AUTO: 1,
    MANUAL: 2,
  },
  CRON_GENERATE_TYPE: {
    AUTO: 1,
    MANUAL: 2,
  },
  POLICY_GENERATE_TYPE: {
    AUTO: 1,
    MANUAL: 2,
  },
  DEVICE_ACTION_TYPE: {
    AUTO: 1,
    MANUAL: 2,
  },
  PROCESS_STEP_TYPE: {
    PENDING: 1,
    COMPLETE: 2,
  },
  TAG_COMPONENT_TYPE: {
    AUTO: 1,
    MANUAL: 2,
  },
  ACTION_VALIDATION_TYPE: {
    AUTO: 1,
    MANUAL: 2,
  },
  CONVERTED_VIEW_DETAIL: {
    AUTO: 1,
    MANUAL: 2,
  },
  CUSTOM_ACTION_VALIDATION_TYPE: {
    AUTO: 1,
    MANUAL: 2,
  },
  SCREEN_WISE_INFO_TYPE: {
    AUTO: 1,
    MANUAL: 2,
  },
};
