export const ListBoxCss = {
  listWrap: 'border-t-1 border-gray-200 cursor-pointer relative',
  listWrapPopup: 'border-t-1 border-gray-100 cursor-pointer relative',
  listnormal: 'py-3 px-1',
  listflat: 'xl:border-none xxl:border-none',
  listsmall: 'py-2 px-1',
  listpopupBox: 'border-t-1 border-gray-100',
  listheadBox: 'p-0 border-1 rounded-3',
  listbottomOutline: 'p-4 border-l-0 border-r-0 border-t-0 border-b-0 ml-2 mr-2',
  listSelected: 'border-primary-dark',
  listLink: 'primary-gray-text-color font-semibold text-sm md:text-base mr-2',
  listHead: 'bg-gray-200 p-3 flex items-center',
  listTitle: 'primary-gray-text-color text-sm',
  listsmallTitle: 'primary-gray-text-color text-xs',
  listIconBox: 'flex items-center cursor-pointer',
  listIconWrap: 'flex items-center justify-end',
  listIconnormal: 'mr-2 w-3.5 h-3.5',
  listIconsmall: 'mr-1 w-3 h-3',
  listTitleBox: 'text-gray-20',
  listIcontitlenormal: 'text-sm',
  listIcontitlesmall: 'text-xs',
  listIconHr: 'mx-4 w-px h-4 my-1 bg-gray-400 block',
};
