export const InformessageCss = {
  messagebox: 'relative flex items-start rounded-3 border-l-4',
  messagenormal: 'p-3',
  messagesmall: 'p-2',
  messageimg: 'flex-shrink-0',
  messageImgnormal: 'w-4 mr-3 ',
  messageImgsmall: 'w-3.5 mr-2',
  messagedec: 'text-primary-message font-bold flex-grow',
  messageTextnormal: 'text-sm',
  messageTextsmall: 'text-xs',
  messageclose: 'w-4 h-4 object-contain m-auto absolute right-5 top-0 bottom-0 cursor-pointer',
  messageinfo: 'bg-secondary-bluelight border-secondary-blue',
  messagewarring: 'bg-secondary-yellowlight border-secondary-yellow',
  messagealert: 'bg-secondary-redlight border-gray-deactivebg',
};
