name: Check ESLint on Pull Request

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: installing eslint 
        run: npm install eslint -g && npm install eslint-plugin-react --save-dev
      - name: installing dev dependencies 
        run: npm install --only=dev
      - name: Fixing Files
        run: eslint . --ext .js --fix
